# Generated by Django 5.0 on 2023-12-19 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('pname', models.CharField(max_length=100)),
                ('pprice', models.CharField(max_length=100)),
                ('sdescrip', models.TextField()),
                ('ldescrip', models.TextField()),
                ('quantity', models.CharField(max_length=100)),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomApp.categories')),
            ],
        ),
    ]
