# Generated by Django 5.0 on 2023-12-27 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_image',
            old_name='imag',
            new_name='image',
        ),
    ]
