# Generated by Django 5.0 on 2023-12-31 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0007_orderupdate_alter_orders_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='item_json',
            new_name='items_json',
        ),
    ]
