# Generated by Django 5.0 on 2024-04-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0010_remove_sign_id_alter_sign_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SIGN',
            new_name='SIGNN',
        ),
    ]
