# Generated by Django 5.0 on 2024-04-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0012_signnn_delete_signn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SIGNNN',
        ),
    ]
