# Generated by Django 5.0 on 2024-04-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0014_signnn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SIGNNN',
            new_name='SIGN',
        ),
    ]
