# Generated by Django 5.0 on 2024-04-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0016_signn_delete_sign'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signn',
            new_name='SIGN',
        ),
    ]
