# Generated by Django 5.0 on 2024-04-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0018_usersign_delete_sign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usersign',
        ),
    ]
