# Generated by Django 5.0 on 2024-04-26 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0019_delete_usersign'),
    ]

    operations = [
    ]
