# Generated by Django 5.0 on 2024-04-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0020_auto_20240426_1845'),
    ]

    operations = [
    ]
