# Generated by Django 5.0 on 2024-04-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0022_sign'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='sign',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, default=5, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='sign',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
