# Generated by Django 5.0 on 2024-04-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0023_sign_id_alter_sign_email'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='sign',
        #     name='id',
        # ),
        migrations.AlterField(
            model_name='sign',
            name='email',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
