# Generated by Django 5.0 on 2024-04-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0024_remove_sign_id_alter_sign_email'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='sign',
        #     name='id',
        # ),
    ]
